import { useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

export type AORenewal = {
  id?: string;
  customer_name: string;
  policy_number: string;
  policy_type: string;
  renewal_date: string;
  current_premium?: number;
  current_carrier?: string;
  status?: "pending" | "contacted" | "quoted" | "won" | "lost";
  priority?: "low" | "normal" | "high" | "urgent";
  assigned_to?: string;
  notes?: string;
  custom_data?: Record<string, any>;
  created_at?: string;
  updated_at?: string;
};

export type AORenewalInsert = Omit<AORenewal, "id" | "created_at" | "updated_at">;

export type ImportResult = {
  successful: number;
  failed: number;
  duplicates: number;
  errors: string[];
};

export const useImportAORenewals = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({
      data,
      filename,
      importType = "initial",
    }: {
      data: Partial<AORenewal>[];
      filename: string;
      importType?: "initial" | "update";
    }): Promise<ImportResult> => {
      const result: ImportResult = {
        successful: 0,
        failed: 0,
        duplicates: 0,
        errors: [],
      };

      // Get current user
      const {
        data: { user },
      } = await supabase.auth.getUser();
      if (!user) {
        throw new Error("User not authenticated");
      }

      // Process each renewal
      for (const renewal of data) {
        try {
          // Validate required fields
          if (!renewal.customer_name || !renewal.policy_number || !renewal.policy_type || !renewal.renewal_date) {
            result.errors.push(`Missing required fields for renewal: ${renewal.policy_number || 'unknown'}`);
            result.failed++;
            continue;
          }

          // Check for duplicates by policy number
          const { data: existing, error: checkError } = await supabase
            .from("ao_renewals")
            .select("id")
            .eq("policy_number", renewal.policy_number)
            .maybeSingle();

          if (checkError) {
            console.error("Error checking for duplicates:", checkError);
            result.errors.push(
              `Error checking duplicate for ${renewal.policy_number}: ${checkError.message}`
            );
            result.failed++;
            continue;
          }

          if (existing) {
            // Duplicate found
            if (importType === "update") {
              // Update existing record (updated_at is auto-generated by trigger)
              const { error: updateError } = await supabase
                .from("ao_renewals")
                .update(renewal as any)
                .eq("id", existing.id);

              if (updateError) {
                console.error("Error updating renewal:", updateError);
                result.errors.push(
                  `Error updating ${renewal.policy_number}: ${updateError.message}`
                );
                result.failed++;
              } else {
                result.successful++;
              }
            } else {
              // Skip duplicate on initial import
              result.duplicates++;
            }
            continue;
          }

          // Prepare insert data - exclude id, created_at, updated_at
          const insertData: AORenewalInsert = {
            customer_name: renewal.customer_name,
            policy_number: renewal.policy_number,
            policy_type: renewal.policy_type,
            renewal_date: renewal.renewal_date,
            current_premium: renewal.current_premium,
            current_carrier: renewal.current_carrier,
            status: renewal.status,
            priority: renewal.priority,
            assigned_to: renewal.assigned_to,
            notes: renewal.notes,
            custom_data: renewal.custom_data,
          };

          // Insert new record (created_at and updated_at are auto-generated)
          const { error: insertError } = await supabase
            .from("ao_renewals")
            .insert([insertData]);

          if (insertError) {
            console.error("Error inserting renewal:", insertError);
            result.errors.push(
              `Error inserting ${renewal.policy_number}: ${insertError.message}`
            );
            result.failed++;
          } else {
            result.successful++;
          }
        } catch (error) {
          console.error("Unexpected error processing renewal:", error);
          result.errors.push(
            `Unexpected error for ${renewal.policy_number}: ${
              error instanceof Error ? error.message : "Unknown error"
            }`
          );
          result.failed++;
        }
      }

      return result;
    },
    onSuccess: (result) => {
      queryClient.invalidateQueries({ queryKey: ["ao-renewals"] });
      
      if (result.failed === 0) {
        toast.success(`Successfully imported ${result.successful} renewals!`);
      } else {
        toast.warning(
          `Import completed with ${result.successful} successes and ${result.failed} failures`
        );
      }
    },
    onError: (error) => {
      console.error("Import failed:", error);
      toast.error("Failed to import renewals. Please try again.");
    },
  });
};
