/**
 * Retention Task Auto-Generation Hook
 *
 * Automatically creates tasks for high-risk customers based on:
 * - Churn probability thresholds
 * - Recommended actions from risk scoring
 * - Renewal urgency
 *
 * Integrates predictive analytics with task management
 */

import { useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import type { CustomerRiskScore } from './usePredictiveAnalytics';

interface GenerateRetentionTasksParams {
  riskScoreId: string;
  accountId: string;
  accountName: string;
  churnProbability: number;
  churnRiskLevel: string;
  recommendedActions: Array<{
    action: string;
    priority: string;
    due_days: number;
    rationale: string;
  }>;
  daysUntilRenewal: number | null;
}

/**
 * Generate retention tasks from risk score
 * Silent operation - no toast notifications
 */
export function useGenerateRetentionTasks() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (params: GenerateRetentionTasksParams) => {
      const { accountId, accountName, recommendedActions, churnProbability, churnRiskLevel, daysUntilRenewal } = params;

      // Only generate tasks for medium risk and above
      if (churnRiskLevel === 'low') {
        return { tasksCreated: 0, message: 'Risk level too low for task generation' };
      }

      const tasksToCreate = [];

      // Generate tasks from recommended actions
      for (const action of recommendedActions.slice(0, 3)) { // Limit to top 3 actions
        const dueDate = new Date();
        dueDate.setDate(dueDate.getDate() + action.due_days);

        const taskTitle = `${action.action} - ${accountName}`;
        const taskDescription = `${action.rationale}

**Churn Risk:** ${churnProbability}% (${churnRiskLevel.toUpperCase()})
**Days Until Renewal:** ${daysUntilRenewal !== null ? daysUntilRenewal : 'Unknown'}

This task was automatically generated by the Predictive Analytics Engine based on customer risk factors.`;

        tasksToCreate.push({
          account_id: accountId,
          title: taskTitle,
          description: taskDescription,
          task_type: 'retention',
          priority: action.priority === 'urgent' ? 'high' : action.priority,
          status: 'todo',
          due_date: dueDate.toISOString(),
          metadata: {
            source: 'predictive_analytics',
            risk_score_id: params.riskScoreId,
            churn_probability: churnProbability,
            churn_risk_level: churnRiskLevel,
            action_type: action.action,
          },
        });
      }

      // Create all tasks in batch
      if (tasksToCreate.length > 0) {
        const { data, error } = await supabase
          .from('tasks')
          .insert(tasksToCreate)
          .select();

        if (error) throw error;

        return {
          tasksCreated: data?.length || 0,
          tasks: data,
          message: `Created ${data?.length || 0} retention task${data?.length !== 1 ? 's' : ''}`,
        };
      }

      return { tasksCreated: 0, message: 'No tasks to create' };
    },
    onSuccess: (data) => {
      if (data.tasksCreated > 0) {
        queryClient.invalidateQueries({ queryKey: ['tasks'] });
      }
    },
    onError: (error: Error) => {
      console.error('Failed to generate retention tasks:', error);
    },
  });
}

/**
 * Auto-generate tasks for all high-risk customers
 * Use this for batch processing or scheduled jobs
 */
export function useBulkGenerateRetentionTasks() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ riskThreshold = 60 }: { riskThreshold?: number }) => {
      // Fetch high-risk customers with risk scores
      const { data: riskScores, error } = await supabase
        .from('customer_risk_scores')
        .select(`
          id,
          account_id,
          churn_probability,
          churn_risk_level,
          days_until_renewal,
          recommended_actions,
          accounts!customer_risk_scores_account_id_fkey(name)
        `)
        .gte('churn_probability', riskThreshold)
        .gt('expires_at', new Date().toISOString())
        .order('churn_probability', { ascending: false });

      if (error) throw error;

      if (!riskScores || riskScores.length === 0) {
        return { customersProcessed: 0, tasksCreated: 0, message: 'No high-risk customers found' };
      }

      let totalTasksCreated = 0;

      // Generate tasks for each high-risk customer
      for (const score of riskScores) {
        const accountName = (score.accounts as any)?.name || 'Unknown Customer';
        const recommendedActions = score.recommended_actions || [];

        if (recommendedActions.length === 0) continue;

        const tasksToCreate = [];

        for (const action of recommendedActions.slice(0, 3)) {
          const dueDate = new Date();
          dueDate.setDate(dueDate.getDate() + action.due_days);

          tasksToCreate.push({
            account_id: score.account_id,
            title: `${action.action} - ${accountName}`,
            description: `${action.rationale}

**Churn Risk:** ${score.churn_probability}% (${score.churn_risk_level.toUpperCase()})
**Days Until Renewal:** ${score.days_until_renewal !== null ? score.days_until_renewal : 'Unknown'}

This task was automatically generated by the Predictive Analytics Engine.`,
            task_type: 'retention',
            priority: action.priority === 'urgent' ? 'high' : action.priority,
            status: 'todo',
            due_date: dueDate.toISOString(),
            metadata: {
              source: 'predictive_analytics',
              risk_score_id: score.id,
              churn_probability: score.churn_probability,
              churn_risk_level: score.churn_risk_level,
              action_type: action.action,
            },
          });
        }

        if (tasksToCreate.length > 0) {
          const { data: createdTasks, error: taskError } = await supabase
            .from('tasks')
            .insert(tasksToCreate)
            .select();

          if (!taskError) {
            totalTasksCreated += createdTasks?.length || 0;
          }
        }
      }

      return {
        customersProcessed: riskScores.length,
        tasksCreated: totalTasksCreated,
        message: `Processed ${riskScores.length} customers, created ${totalTasksCreated} tasks`,
      };
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['tasks'] });
    },
    onError: (error: Error) => {
      console.error('Bulk task generation failed:', error);
    },
  });
}

/**
 * Check if retention tasks already exist for this risk score
 * Prevents duplicate task creation
 */
export async function hasExistingRetentionTasks(riskScoreId: string): Promise<boolean> {
  const { data, error } = await supabase
    .from('tasks')
    .select('id')
    .eq('task_type', 'retention')
    .contains('metadata', { risk_score_id: riskScoreId })
    .limit(1);

  if (error) {
    console.error('Error checking existing tasks:', error);
    return false;
  }

  return (data?.length || 0) > 0;
}
